---
- name: Add GPG keys
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: '0644'
    force: true
  loop: "{{ urls }}"

- name: Add repos
  ansible.builtin.apt_repository:
    filename: "{{ item.name }}"
    repo: "{{ item.repo }}"
  loop: "{{ repos }}"