---
tasks:
- name: Add GPG keys
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: '0644'
    force: true

- name: Add repos
  ansible.builtin.apt_repository:
    filename: brave-browser
    repo: "{{ repos }}"
